--DROP TABLE MASTER_DATA;
CREATE TABLE MASTER_DATA
(
     ID NUMBER(10) PRIMARY KEY,
     TITLE VARCHAR2(50) NOT NULL,
     DESCRIPTION VARCHAR2(50) NOT NULL,
     ACTIVE_YN CHAR(1) NOT NULL,
     FILE_NAME VARCHAR2(20) NOT NULL,
     FILE_CONTENT BLOB,
     CONTENT_TYPE VARCHAR2(10) GENERATED ALWAYS AS (CASE WHEN FILE_CONTENT IS NOT NULL THEN 'STORED' ELSE 'FAILED' END),
     ACTION_ON DATE DEFAULT (SYSDATE)
);

INSERT INTO MASTER_DATA 
(ID,TITLE,DESCRIPTION,ACTIVE_YN,FILE_NAME,FILE_CONTENT)
VALUES 
(1,'Test','testing on master data','Y','test.xlsx',null);
-----------------------------------------------------------
INSERT INTO MASTER_DATA 
(ID,TITLE,DESCRIPTION,ACTIVE_YN,FILE_NAME,FILE_CONTENT,REQUEST_ON,COMPLETE_ON)
VALUES 
(2,'Test2','testing2 on master data','Y','test.xlsx',null,systimestamp-1, systimestamp);

ALTER TABLE MASTER_DATA ADD REQUEST_ON TIMESTAMP;
ALTER TABLE MASTER_DATA ADD COMPLETE_ON TIMESTAMP;
ALTER TABLE MASTER_DATA ADD TIME_TAKEN VARCHAR2(5);